### ISSUE TITLE
Przygotowanie repo do czwartkowego spotkania

### ISSUE THREAD

**Issue by finloop** [knmlprz/SimpleDiscordBot#1]
Repo można znaleźć tu: https://github.com/knmlprz/SimpleDiscordBot

**Comment by TheJimmyNowak** [comment]
Z tego repo zrobiłbym [template](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository) i chciałbym, żeby sobie działali na własnych repo (idealnie jeden zespół jedno repo). To wtedy flow było by takie

Ktoś kopiuje repo na swoje -> i wtedy dopiero ludzie klonują to repo

Ja w prezentacji wytłumaczę jak mają sobie robicz branche i commity ^^ A na koniec zrobią sobie PRa  i review. W taki magiczny sposób przejdą (prawie) cały proces dodawania zmian.

Jeżeli się podoba to checklista dla cb ;*
- [ ] Zrobić template
- [ ] Zmienić readme

**Comment by finloop** [comment]
- [x] Zrobić template
- [x] Zmienić readme

@TheJimmyNowak

**Comment by TheJimmyNowak** [comment]
![image](https://github.com/knmlprz/SimpleDiscordBot/assets/32245772/e2605843-f7ae-4a00-b7fa-100c61bed0bc)
